namespace MemoryTimeline.Core.Services;

/// <summary>
/// Service interface for generating and managing text embeddings.
/// </summary>
public interface IEmbeddingService
{
    /// <summary>
    /// Generates an embedding vector for text.
    /// </summary>
    /// <param name="text">Text to embed</param>
    /// <returns>Embedding vector</returns>
    Task<float[]> GenerateEmbeddingAsync(string text);

    /// <summary>
    /// Generates embeddings for multiple texts in a batch.
    /// </summary>
    /// <param name="texts">Texts to embed</param>
    /// <returns>List of embedding vectors</returns>
    Task<List<float[]>> GenerateEmbeddingsAsync(IEnumerable<string> texts);

    /// <summary>
    /// Calculates cosine similarity between two embeddings.
    /// </summary>
    /// <param name="embedding1">First embedding</param>
    /// <param name="embedding2">Second embedding</param>
    /// <returns>Similarity score (0.0 to 1.0)</returns>
    double CalculateCosineSimilarity(float[] embedding1, float[] embedding2);

    /// <summary>
    /// Finds the K most similar embeddings to a query embedding.
    /// </summary>
    /// <param name="queryEmbedding">Query embedding</param>
    /// <param name="candidateEmbeddings">Candidate embeddings with IDs</param>
    /// <param name="k">Number of results to return</param>
    /// <param name="threshold">Minimum similarity threshold (optional)</param>
    /// <returns>List of similar items with similarity scores</returns>
    List<SimilarityResult> FindKNearestNeighbors(
        float[] queryEmbedding,
        IEnumerable<(string id, float[] embedding)> candidateEmbeddings,
        int k,
        double threshold = 0.0);

    /// <summary>
    /// Gets the dimension of embeddings generated by this service.
    /// </summary>
    int EmbeddingDimension { get; }

    /// <summary>
    /// Gets the name of the embedding model.
    /// </summary>
    string ModelName { get; }

    /// <summary>
    /// Gets whether the service requires internet connectivity.
    /// </summary>
    bool RequiresInternet { get; }
}

/// <summary>
/// Result of a similarity search.
/// </summary>
public class SimilarityResult
{
    /// <summary>
    /// ID of the similar item.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Similarity score (0.0 to 1.0).
    /// </summary>
    public double Similarity { get; set; }
}
