// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using MemoryTimeline.Data;

#nullable disable

namespace MemoryTimeline.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // This is a simplified model snapshot
            // The actual snapshot would be generated by EF Core migrations
            // when running: dotnet ef migrations add InitialCreate
#pragma warning restore 612, 618
        }
    }
}
