namespace MemoryTimeline.SyncApi.Domain;

/// <summary>
/// One assistant conversation (design §6.6, §19 Phase 4). A session exists so
/// turns have an order and a shared preferred responder; it holds no context of
/// its own, because the archive it would be context over lives on Windows.
///
/// <see cref="DeviceId"/> is the ownership boundary for the assistant API: only
/// the device that opened a session may add turns to it or read it. That is
/// deliberately narrower than the owner-scoping the rest of the service uses —
/// a conversation is a live interaction with one surface, and a second phone
/// reading it would be eavesdropping rather than syncing.
/// </summary>
public class AssistantSessionRow
{
    /// <summary>Session ID (GUID, "D" format), generated by the service.</summary>
    public string SessionId { get; set; } = string.Empty;

    public string OwnerId { get; set; } = string.Empty;

    /// <summary>Device that opened the session; the only one allowed to use it.</summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>Responder used by turns that do not name one (AssistantResponder values).</summary>
    public string PreferredResponder { get; set; } = string.Empty;

    /// <summary>Free-text surface label for diagnostics only; never used for routing.</summary>
    public string? Surface { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    /// <summary>Last accepted turn, so idle sessions can be reaped later.</summary>
    public DateTime LastTurnAtUtc { get; set; }

    /// <summary>Accepted turns so far; also the source of the next turn's sequence.</summary>
    public int TurnCount { get; set; }
}

/// <summary>
/// One question and, eventually, its answer (design §6.6, §19 Phase 4).
///
/// This row is a routing record, not a transcript: the service stores the turn
/// so a client can poll it and so a late answer has somewhere to land, but it
/// never produces the answer itself — a responder does, and pushes it back
/// through the change feed. The columns therefore mirror
/// <c>AssistantTurnChangePayload</c> almost field for field, so a pushed
/// revision applies without translation and a pulled payload can be
/// re-serialized straight from what was stored.
///
/// <see cref="OriginDeviceId"/> is copied from the session at creation rather
/// than joined on read: every ownership check and every published payload needs
/// it, and denormalizing it keeps the push path (which knows a turn ID and
/// nothing else) off the sessions table entirely.
///
/// Nothing here is ever logged beyond the identifiers and the status
/// (design §14.5): <see cref="Question"/>, <see cref="Answer"/>,
/// <see cref="CitationsJson"/> and <see cref="ClientContextJson"/> all carry
/// personal memory content.
/// </summary>
public class AssistantTurnRow
{
    /// <summary>Client-generated turn ID (GUID, "D" format) — the idempotency key for submission.</summary>
    public string TurnId { get; set; } = string.Empty;

    public string SessionId { get; set; } = string.Empty;

    public string OwnerId { get; set; } = string.Empty;

    /// <summary>
    /// Device that asked, copied from the session. Answers may arrive from any
    /// of the owner's devices, but only this one may read the turn back.
    /// </summary>
    public string OriginDeviceId { get; set; } = string.Empty;

    /// <summary>Monotonic within the session, assigned by the service.</summary>
    public int Sequence { get; set; }

    /// <summary>The question text. Never logged (design §14.5).</summary>
    public string Question { get; set; } = string.Empty;

    /// <summary>Lifecycle state (AssistantTurnStatus values).</summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>Responder the client asked for (AssistantResponder values).</summary>
    public string RequestedResponder { get; set; } = string.Empty;

    /// <summary>
    /// Responder that actually answered; null until something claims the turn.
    /// Kept alongside <see cref="RequestedResponder"/> rather than overwriting
    /// it so a client can tell that its request for Windows was served by a
    /// fallback, which is exactly the case where the answer is less grounded.
    /// </summary>
    public string? ActualResponder { get; set; }

    /// <summary>
    /// Device-supplied grounding as a serialized AssistantContextItem list, or
    /// null when the turn carried none. Stored verbatim (after validation) so
    /// the published payload is byte-identical to what the client sent — a
    /// responder must see the whole context or none of it. Never logged.
    /// </summary>
    public string? ClientContextJson { get; set; }

    /// <summary>Whether the client asked for incremental chunks; advisory to the responder.</summary>
    public bool Stream { get; set; }

    /// <summary>The answer text once completed. Never logged (design §14.5).</summary>
    public string? Answer { get; set; }

    /// <summary>How well anchored the answer is (AssistantGrounding values); null until answered.</summary>
    public string? Grounding { get; set; }

    /// <summary>
    /// Serialized AssistantCitation list backing the answer. An empty list is
    /// meaningful and distinct from null: it is an honest refusal from a
    /// responder that found nothing, whereas null means nothing has answered
    /// yet. Never logged (excerpts are archive content).
    /// </summary>
    public string? CitationsJson { get; set; }

    /// <summary>Model that produced the answer, for display and diagnostics.</summary>
    public string? Model { get; set; }

    /// <summary>Wall-clock milliseconds the responder reported taking.</summary>
    public int? ElapsedMs { get; set; }

    /// <summary>
    /// Display-safe failure text; by contract carries no paths or credentials
    /// (design §14.5).
    /// </summary>
    public string? FailureReason { get; set; }

    public bool? FailureRetryable { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    /// <summary>
    /// When the last accepted revision was recorded. Carried into the published
    /// payload for display and last-write-wins tie-breaking, exactly as the
    /// capture status projection does.
    /// </summary>
    public DateTime UpdatedAtUtc { get; set; }

    /// <summary>Set when the turn reached a terminal state, whichever one.</summary>
    public DateTime? CompletedAtUtc { get; set; }

    /// <summary>Monotonic per-turn revision, carried on every change row it produces.</summary>
    public long Revision { get; set; }
}
